version: '3'
services:
  proxysql:
    image: proxysql/proxysql:2.0.17
    container_name: proxysql
    volumes:
      - ./conf/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - "6032:6032"
      - "6033:6033"
      - "6080:6080"
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    restart: always
  phpmyadmin_proxysql:
    container_name: phpmyadmin_proxysql
    hostname: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./conf/phpmyadmin_proxysql/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./data/phpmyadmin_proxysql/:/srv/phpmyadmin/
    ports:
      - 80:80
    environment:
      PMA_HOST: proxysql
      PMA_PORT: 6032
      PMA_USER: admin
      PMA_PASSWORD: adminadmin
      MYSQL_ROOT_PASSWORD: adminadmin
      UPLOAD_LIMIT: "100M"
    depends_on:
      - proxysql