version: "3"
services:
  proxysql:
    build:
        context: ./docker
        dockerfile: Dockerfile.sqlite
    image: proxysql_sqlite
    container_name: proxysql
    hostname: proxysql
    volumes:
      - ./conf/proxysql.cnf:/etc/proxysql.cnf
      - ./data/proxysql:/var/lib/proxysql
      - ./data/mysql:/var/lib/mysql
      - ./script/gr_sw_mode_checker.sh:/var/lib/proxysql/gr_sw_mode_checker.sh
      - ./logs/gr_sw_mode_checker.log:/var/lib/proxysql/gr_sw_mode_checker.log
    ports:
      - "6032:6032"
      - "6033:6033"
      - "6080:6080"
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    restart: always
    networks:
      - mysql_network
  sqlite-web:
    # https://github.com/coleifer/sqlite-web
    image: coleifer/sqlite-web
    container_name: sqlite-web
    hostname: sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data/proxysql:/data
    command: ["sqlite_web", "/data/proxysql.db", "--host", "0.0.0.0"]

networks:
  mysql_network:
    external:
      name: mysql_network
