version: "3"
services:
  proxysql:
    build:
        context: ./docker
        dockerfile: Dockerfile.sqlite
    image: proxysql_sqlite
    container_name: proxysql
    hostname: proxysql
    volumes:
      - ./conf/proxysql.cnf:/etc/proxysql.cnf
      - ./data/proxysql:/var/lib/proxysql
    ports:
      - "6032:6032"
      - "6033:6033"
      - "6080:6080"
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    restart: always
    networks:
      - mysql_network

networks:
  mysql_network:
    external:
      name: mysql_network
